## 20 Numpy Methods With Examples

### Creating array
1.	Random integers in a specific range

In [2]:
#Example1: single line array of integers between 0 and 5
import numpy as np
np.random.randint(5, size=7)

array([3, 0, 2, 1, 2, 0, 2])

In [7]:
#Example 2:  2x3 array of integers between 2 and 10.
np.random.randint(2,10, size=(2,3))

array([[8, 6, 7],
       [8, 7, 8]])

2. Random floats between 0 and 1

In [9]:
#Example (used to create random data values between 0 and 1)
np.random.random(8)

array([0.21450386, 0.41931824, 0.61071708, 0.31586001, 0.47290573,
       0.95791381, 0.21756898, 0.70026085])

3. Sample from a standard normal distribution



In [11]:
#Example (np.random.randn() is used to create a sample from a standard normal distribution (i.e. zero mean and unit variance).)
print(np.random.rand(100).mean())
print(np.random.rand(100).std())  #we created an array of 100 floats

0.5112012939195355
0.28702548083064044


4. Matrix with ones and zeros



In [ ]:
#A matrix can be considered as a 2-dimensional array. 
#We can create a matrix with zeros or ones with np.zeros and np.ones, respectively.

In [12]:
#matrix with ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#matrix with Zeros
np.zeros(10)   #We can specify the dimension of the matrix as we like

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

5. Identity matrix



In [15]:
#An identity matrix is a square matrix (nxn) that has ones on the diagonal and zeros on every other position.
#Np.eye or np.identity can be used to create one.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

6. Arange



In [17]:
#Arange function is used to create arrays with evenly spaced sequential values in a specified interval. 
#We can specify start value, stop value, and step size. 
#The default start value is zero and the default step size is one.

In [18]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
np.arange(3,7)

array([3, 4, 5, 6])

In [22]:
np.arange(30,100,6)

array([30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

7. Array with only one value


In [ ]:
#We can create an array that has the same value at every position using np.full.


In [24]:
#Example1:
np.full((3,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [27]:
#Example2:
np.full((3,4) ,8, dtype ='float') #dtype is used to change parameter. The default data type is integer.

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

#### Manipulating arrays



In [32]:
#Let’s first create a 2-dimensional array:
A =np.random.randint(5 ,size=(3,4))
A

array([[2, 0, 3, 4],
       [0, 0, 0, 0],
       [3, 0, 0, 0]])

8. Ravel



In [ ]:
#Ravel function flattens the array (i.e. converts it to a 1-dimensional array).

In [33]:
#Example1:
A.ravel()

array([2, 0, 3, 4, 0, 0, 0, 0, 3, 0, 0, 0])

In [36]:
#Example2:
A.ravel(order = 'F')  #By default, an array is flattened by adding row after row. 
                      #It can be changed to column-wise by setting the order parameter as F (Fortran-style).

array([2, 0, 3, 0, 0, 0, 3, 0, 0, 4, 0, 0])

9. Reshape


In [40]:
#As the same suggests, it reshapes an array. The shape of A is (3,4) and the size is 12.
#to confirm this:
A.shape

(3, 4)

In [39]:
A.size

12

In [42]:
A #to remind us of what A is

array([[2, 0, 3, 4],
       [0, 0, 0, 0],
       [3, 0, 0, 0]])

In [41]:
#We need to preserve the size of A which is the product of the sizes in each dimension.
A.reshape(4,3)

array([[2, 0, 3],
       [4, 0, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [46]:
A.reshape(2,6)

array([[2, 0, 3, 4, 0, 0],
       [0, 0, 3, 0, 0, 0]])

In [47]:
#We don’t have to specify the size in every dimension. We can let NumPy to figure out a dimension by passing -1.
A.reshape(-1,3)

array([[2, 0, 3],
       [4, 0, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [51]:
A.reshape(1,-1)

array([[2, 0, 3, 4, 0, 0, 0, 0, 3, 0, 0, 0]])

10. Transpose



In [52]:
#Transposing a matrix is to switch rows and columns.
A

array([[2, 0, 3, 4],
       [0, 0, 0, 0],
       [3, 0, 0, 0]])

In [53]:
A.transpose()

array([[2, 0, 3],
       [0, 0, 0],
       [3, 0, 0],
       [4, 0, 0]])

11. Vsplit



In [54]:
#Splits an array into multiple sub-arrays vertically.
A= np.random.randint(5, size=(4,3))
A

array([[4, 1, 3],
       [0, 2, 2],
       [4, 1, 1],
       [0, 1, 1]])

In [56]:
np.vsplit(A,2)

[array([[4, 1, 3],
        [0, 2, 2]]),
 array([[4, 1, 1],
        [0, 1, 1]])]

In [ ]:
#In the example above, We split a 4x3 array into 2 sub-arrays, each having a shape of 2x3.

In [57]:
#We can access a particular sub-array after splitting.
np.vsplit(A,2)[0]

array([[4, 1, 3],
       [0, 2, 2]])

12. Hsplit



In [ ]:
#It is similar to vsplit but works horizontally.

In [3]:
#Example:
a = np.random.randint(5, size=12)
a

array([1, 0, 4, 0, 1, 0, 2, 1, 0, 4, 3, 0])

In [5]:
np.hsplit(a,2)

[array([1, 0, 4, 0, 1, 0]), array([2, 1, 0, 4, 3, 0])]

In [8]:
#If we apply hsplit on a 6x3 arrays to get 3 sub-arrays, resulting arrays will have a shape of (6,1).
b = np.random.randint(5, size=(6,3))
np.hsplit(b, 3)[0]

array([[3],
       [4],
       [0],
       [3],
       [2],
       [0]])

In [9]:
np.hsplit(b, 3)[0].shape

(6, 1)

### Combining arrays

13. Concatenate



In [10]:
#It is similar to the concat function of pandas.
#Example:
a = np.array([1,2,3,4])
b = np.array([7,8,9,0])
np.concatenate((a,b))

array([1, 2, 3, 4, 7, 8, 9, 0])

In [13]:
#We can convert a and b arrays above to column vectors using the reshape function and then concatenate vertically.
#Example:
np.concatenate((a.reshape(-1, 1),  b.reshape(-1,1)),  axis =1)

array([[1, 7],
       [2, 8],
       [3, 9],
       [4, 0]])

14. Vstack



In [14]:
#It is used to stack arrays vertically (rows on top of each other).
#Example:
a = np.array([1,2,3,4])
b = np.array([7,8,9,0])
c = np.array([11,12,13,14])
d = np.array([17,18,19,20])
np.vstack((a,b,c,d))

array([[ 1,  2,  3,  4],
       [ 7,  8,  9,  0],
       [11, 12, 13, 14],
       [17, 18, 19, 20]])

In [17]:
#It also works with higher dimensional arrays.
#Example:
A =np.random.randint(6, size =(2,2,2))
B =np.random.randint(6, size =(2,2,2))
C =np.random.randint(6, size =(2,2,2))
np.vstack((A,B,C))

array([[[0, 5],
        [3, 1]],

       [[0, 0],
        [5, 2]],

       [[0, 5],
        [3, 5]],

       [[4, 0],
        [2, 1]],

       [[0, 5],
        [2, 5]],

       [[0, 4],
        [4, 4]]])

15. Hstack



In [18]:
#Similar to vstack but works horizontally (column-wise).
#Example:
a = np.array([1,2,3,4]).reshape(-1,1)
b = np.array([7,8,9,0]).reshape(-1,1)
c = np.array([11,12,13,14]).reshape(-1,1)
np.hstack((a,b,c))

array([[ 1,  7, 11],
       [ 2,  8, 12],
       [ 3,  9, 13],
       [ 4,  0, 14]])

### Linear algebra with NumPy arrays (numpy.linalg)

16. Det

In [22]:
#Returns the determinant of a matrix.
#Example:
A = np.random.randint(5, size=(3,3))
A

array([[1, 3, 0],
       [2, 4, 4],
       [4, 3, 0]])

In [23]:
np.linalg.det(A)

36.0

In [ ]:
#A matrix must be square (i.e. the number of rows is equal to the number of columns) to calculate the determinant. 
#For a higher-dimensional array, the last two dimensions must be square.

17. Inv

In [24]:
#Calculates the inverse of a matrix.
np.linalg.inv(A)

array([[-0.33333333,  0.        ,  0.33333333],
       [ 0.44444444,  0.        , -0.11111111],
       [-0.27777778,  0.25      , -0.05555556]])

In [ ]:
#Note: 
#The inverse of a matrix is the matrix that gives the identity matrix when multiplied with the original matrix. 
#Not every matrix has an inverse. If matrix A has an inverse, then it is called invertible or non-singular.

18. Eig



In [26]:
#Computes the eigenvalues and right eigenvectors for a square matrix.
#Example:
np.linalg.eig(A)

(array([ 7.50469735+0.j        , -1.25234868+1.79683566j,
        -1.25234868-1.79683566j]),
 array([[ 0.36130216+0.j        ,  0.10536598+0.54615733j,
          0.10536598-0.54615733j],
        [ 0.78338708+0.j        , -0.4062253 -0.34693713j,
         -0.4062253 +0.34693713j],
        [ 0.50573257+0.j        ,  0.63657349+0.j        ,
          0.63657349-0.j        ]]))

19. Dot



In [ ]:
#Calculates the dot product of two vectors which is the sum of the products of elements with regards to their position. 
#The first element of the first vector is multiplied by the first element of the second vector and so on.

In [27]:
#Example:
a = np.array([1,2,3,4])
b = np.array([7,8,9,0])
np.dot(a,b)

50

20. Matmul



In [ ]:
#It performs matrix multiplication.
#example:
A = ([[1,2],[3,4]])
B = ([[3,4],[3,1]])
n.p